version: "2.1"
services:

  mysql:
    container_name: mysql
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --server-id=1 --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  firesql:
    image: nyanpass/firesql
    tty: true
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - 8080:8080
