version: "3.7"
services:

  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --server-id=1 --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

  firesql:
    image: nyanpass/firesql
    tty: true
    restart: always
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - 8080:8080
